
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vnscout_backend
    ports:
      - "8081:8081"
    restart: always
    environment:
      # Sửa localhost thành host.docker.internal để Docker gọi ra MySQL trên máy thật
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/VNScout?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      # Các Key quan trọng, Docker sẽ tự động lấy từ file .env cùng thư mục với docker-compose.yml
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - VIETMAP_API_KEY=${VIETMAP_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MODERATION_TOXIC_COMMENT_URL=http://host.docker.internal:8000/check-toxic
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: 
      context: ../VibeCode- ĐATN/v0_photo_scount_v1
      dockerfile: Dockerfile
    container_name: vnscout_frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
